# Generated by Django 4.1.7 on 2023-04-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0002_destino_pasajero_preferencias_delete_curso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destino',
            old_name='fecha',
            new_name='salida',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='bebidas',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='comidas',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='equipaje',
        ),
        migrations.AddField(
            model_name='destino',
            name='hotel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='Incluir bebidas libres durante el vuelo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='Incluir comidas durante el vuelo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='Incluir equipaje de bodeja',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='apellido',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
