# Generated by Django 4.1.7 on 2023-04-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0003_rename_fecha_destino_salida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferencias',
            old_name='Incluir bebidas libres durante el vuelo',
            new_name='bebidas',
        ),
        migrations.RenameField(
            model_name='preferencias',
            old_name='Incluir comidas durante el vuelo',
            new_name='comidas',
        ),
        migrations.RenameField(
            model_name='preferencias',
            old_name='Incluir equipaje de bodeja',
            new_name='equipaje',
        ),
    ]
